server:
  port: 8080
  servlet:
    session:
      timeout: 36000000
spring:
  profiles:
    active: develop
  security:
    oauth2:
      client:
        provider:
          microsoft-identity:
            authorization-uri: https://login.microsoftonline.com/${tenant-id}/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/${tenant-id}/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            jwk-set-uri: https://login.microsoftonline.com/${tenant-id}/discovery/keys
            user-name-attribute: name
        registration:
          graph:
            provider: microsoft-identity
            client-id: ${client-id}
            client-secret: ${client-secret}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/graph"
            scope: openid, profile, offline_access, https://graph.microsoft.com/User.Read, https://graph.microsoft.com/Directory.AccessAsUser.All
          office:
            provider: microsoft-identity
            client-id: ${client-id}
            client-secret: ${client-secret}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/office"
            scope: openid, profile, offline_access, https://manage.office.com/ActivityFeed.Read
          arm:
            provider: microsoft-identity
            client-id: ${client-id}
            client-secret: ${client-secret}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/arm"
            scope: openid, profile, offline_access, https://management.core.windows.net/user_impersonation
